use_frameworks!

platform :ios, '13.0'

target 'EtsyCompositionalLayoutBridge_Example' do
  pod 'EtsyCompositionalLayoutBridge', :path => '../'

  target 'EtsyCompositionalLayoutBridge_Tests' do
    inherit! :search_paths

    
  end
end
